import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import AdminDashboardLayout from "~/components/layouts/admin-dashboard-layout";


const Dashboard: NextPage = () => {
  const session = useSession();
  const router = useRouter();
  if(session.status === "unauthenticated"){
    router.push("/").catch(console.error);
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AdminDashboardLayout>
          Dashboard
        </AdminDashboardLayout>
      </main>
    </>
  );
};

export default Dashboard;